### ISSUE TITLE
How to install on non debian based distro?

### ISSUE THREAD

**Issue by ZerdoX-x** [waydroid/docs#11]

**Comment by ZerdoX-x** [comment]
> I'd also be very interested in this (specifically: Fedora). Thanks!!

Here is [tutorial](https://yanqiyu.info/2021/10/25/waydroid-fedora/) for your distro.
But it's not solving the main problem. We need docs about building project

**Comment by tiziodcaio** [comment]
I think now it is solved

**Comment by tiziodcaio** [comment]
circa

**Comment by LecrisUT** [comment]
If you are referring to 6164cd69c215b353a3f56eb969cd29c0a2fcfe8a, it is better than nothing, but it is not an official documentation, e.g. it does not guarantee it is up to date with the planned development. Due to this inconsistency, I am still unable to get it to run on any of my x86 Fedora KDE environments, and there is no troubleshooting tips to understand why it fails. On the other hand there are plenty of other people who somehow seem to have no problems at all, and it is frustrating to not know what is different.

**Comment by ZerdoX-x** [comment]
Still not able to run it on void linux

**Comment by PhilDevProg** [comment]
@aleasto Why did you close this issue? The issue is about the missing instructions on how to build/run the project no matter which distro you use. You added instructions for Void Linux but that doesn't solve the issue.

**Comment by ZerdoX-x** [comment]
Reopen. My local issue is solved. But what if I change my distro to gentoo, parabola or any other one?

**Comment by ZerdoX-x** [comment]
Ok, so issue is ignored for a month already. I will reopen issue for gentoo and parabola distos and will open another one until full instruction of how to manual build will be added to the docs.
